[package]
name = "bme280-rs"
version = "0.0.2"
authors = ["Yuichiro Hanada <i@chir.jp>"]

[dependencies]
docopt = "*"
i2cdev = "*"
nix = "^0.14"
serde = "*"
serde_derive = "*"

[[bin]]
doc = false
name = "bme280"
path = "src/main.rs"
