[package]
name = "bme280-rs"
version = "0.0.1"
authors = ["Yuichiro Hanada <i@chir.jp>"]

[dependencies]
docopt = "*"
i2cdev = "*"
nix = "*"
serde = "*"
serde_derive = "*"

[[bin]]
doc = false
name = "bme280"
